name: RealPermissions
version: '${project.version}'
main: joserodpt.realpermissions.RealPermissions
api-version: '1.13'
authors: [JoseGamer_PT]
description: Fast and Flexible User Permission Management plugin.
website: https://www.spigotmc.org/members/josegamer_pt.40267/