name: Realpermissions
version: '${project.version}'
main: joserodpt.realpermissions.plugin.RealPermissionsPlugin
api-version: '1.13'
softdepend: [Vault, EssentialsX]
authors: [JoseGamer_PT]
description: Fast and Flexible User Permission Management plugin.
website: https://www.spigotmc.org/members/josegamer_pt.40267/