package joserodpt.realpermissions.api;

/*
 *   _____            _ _____
 *  |  __ \          | |  __ \                  (_)       (_)
 *  | |__) |___  __ _| | |__) |__ _ __ _ __ ___  _ ___ ___ _  ___  _ __  ___
 *  |  _  // _ \/ _` | |  ___/ _ \ '__| '_ ` _ \| / __/ __| |/ _ \| '_ \/ __|
 *  | | \ \  __/ (_| | | |  |  __/ |  | | | | | | \__ \__ \ | (_) | | | \__ \
 *  |_|  \_\___|\__,_|_|_|   \___|_|  |_| |_| |_|_|___/___/_|\___/|_| |_|___/
 *
 * Licensed under the MIT License
 * @author José Rodrigues
 * @link https://github.com/joserodpt/RealPermissions
 */

import joserodpt.realpermissions.api.pluginhookup.ExternalPlugin;
import joserodpt.realpermissions.api.pluginhookup.ExternalPluginPermission;
import org.bukkit.Material;
import org.bukkit.plugin.Plugin;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class RealPermissionsHookupAPI {

    private final RealPermissionsAPI rpa;

    private final Map<String, ExternalPlugin> externalPluginList = new HashMap<>();

    public RealPermissionsHookupAPI(RealPermissionsAPI rpa) { this.rpa = rpa; }

    public void addHookup(ExternalPlugin ep) {
        if (!this.externalPluginList.containsKey(ep.getName())) {
            this.externalPluginList.put(ep.getName(), ep);
            rpa.getLogger().info("Loaded " + ep.getPermissionList().size() + " permissions from " + ep.getName() + ", version: " + ep.getVersion());
        }
    }

    public void removeHookup(ExternalPlugin ep) {
        this.externalPluginList.remove(ep.getName());
    }

    public void injectEssentialsXPermissions(String ver) {
        addHookup(new ExternalPlugin("EssentialsX", "&fEssentialsX", "EssentialsX is the essential plugin suite for Minecraft servers, with over 130 commands for servers of all size and scale.", Material.COMMAND_BLOCK, Arrays.asList(
                new ExternalPluginPermission("essentials.afk", "Allow access to the /afk command.", Collections.singletonList("afk")),
                new ExternalPluginPermission("essentials.afk.message", "Allow access to settings an afk message.", Collections.singletonList("afk")),
                new ExternalPluginPermission("essentials.afk.others", "Allows you to AFK other players.", Collections.singletonList("afk")),
                new ExternalPluginPermission("essentials.afk.auto", "Players with this permission will be set to afk after a period of inaction as defined in the config file.", Collections.singletonList("afk")),
                new ExternalPluginPermission("essentials.afk.kickexempt", "Exempts the user from being auto kicked for AFK", Collections.singletonList("afk")),
                new ExternalPluginPermission("essentials.antioch", "Allow access to the /antioch command.", Collections.singletonList("antioch")),
                new ExternalPluginPermission("essentials.back", "Allow access to the /back command.", Collections.singletonList("back")),
                new ExternalPluginPermission("essentials.back.ondeath", "Give this permission to allow players to use /back to go to their death spot", Collections.singletonList("back")),
                new ExternalPluginPermission("essentials.back.onteleport", "Players with this permission will have back location stored during any teleportation", Collections.singletonList("back")),
                new ExternalPluginPermission("essentials.backup", "Allow access to the /backup command.", Collections.singletonList("backup")),
                new ExternalPluginPermission("essentials.balance", "Allow access to the /balance command.", Collections.singletonList("balance")),
                new ExternalPluginPermission("essentials.balance.others", "Allows you to see the balance of other players", Collections.singletonList("balance")),
                new ExternalPluginPermission("essentials.balancetop", "Allow access to the /balancetop command.", Collections.singletonList("balancetop")),
                new ExternalPluginPermission("essentials.balancetop.force", "Allow a forced refresh of balancetop with /balancetop force", Collections.singletonList("balancetop")),
                new ExternalPluginPermission("essentials.ban", "Allow access to the /ban command.", Collections.singletonList("ban")),
                new ExternalPluginPermission("essentials.ban.exempt", "Prevents a specified group or player from being banned", Collections.singletonList("ban")),
                new ExternalPluginPermission("essentials.ban.offline", "Allows banning of players who are offline.  This may allow you to ban exempt players.", Collections.singletonList("ban")),
                new ExternalPluginPermission("essentials.banip", "Allow access to the /banip command.", Collections.singletonList("banip")),
                new ExternalPluginPermission("essentials.unban", "Allow access to the /unban command.", Collections.singletonList("unban")),
                new ExternalPluginPermission("essentials.unbanip", "Allow access to the /unbanip command.", Collections.singletonList("unbanip")),
                new ExternalPluginPermission("essentials.bigtree", "Allow access to the /bigtree command.", Collections.singletonList("bigtree")),
                new ExternalPluginPermission("essentials.book", "Allow access to the /book command.", Collections.singletonList("book")),
                new ExternalPluginPermission("essentials.book.author", "Allows the user to change the author of a book.", Collections.singletonList("book")),
                new ExternalPluginPermission("essentials.book.others", "Allow editing a book belonging to another player.", Collections.singletonList("book")),
                new ExternalPluginPermission("essentials.book.title", "Allows the user to change the title of a written book", Collections.singletonList("book")),
                new ExternalPluginPermission("essentials.break", "Allows access to the /break command.", Collections.singletonList("break")),
                new ExternalPluginPermission("essentials.break.bedrock", "Allows the breaking of bedrock.", Collections.singletonList("break")),
                new ExternalPluginPermission("essentials.broadcast", "Allow access to the /broadcast command.", Collections.singletonList("broadcast")),
                new ExternalPluginPermission("essentials.broadcastworld", "Allow access to the /broadcastworld command.", Collections.singletonList("broadcastworld")),
                new ExternalPluginPermission("essentials.burn", "Allow access to the /burn command.", Collections.singletonList("burn")),
                new ExternalPluginPermission("essentials.chat.ignoreexempt", "Someone with this permission will not be ignored, even if they are on another persons ignore list."),
                new ExternalPluginPermission("essentials.chat.spy", "A permission designed for admins, to intercept all local messages (ignoring the chat-radius).", Collections.singletonList("me")),
                new ExternalPluginPermission("essentials.chat.spy.exempt", "Allow to be exempt from chat spy"),
                new ExternalPluginPermission("essentials.clearinventory", "Allow access to the /clearinventory command.", Collections.singletonList("clearinventory")),
                new ExternalPluginPermission("essentials.clearinventory.all", "Allows a player to clear all players inventories.", Collections.singletonList("clearinventory")),
                new ExternalPluginPermission("essentials.clearinventory.multiple", "Allow clearing inventory of multiple people at once", Collections.singletonList("clearinventory")),
                new ExternalPluginPermission("essentials.clearinventory.others", "Allows you to clear other player's inventory", Collections.singletonList("clearinventory")),
                new ExternalPluginPermission("essentials.clearinventoryconfirmtoggle", "Allow access to the /clearinventoryconfirmtoggle command", Collections.singletonList("clearinventoryconfirmtoggle")),
                new ExternalPluginPermission("essentials.commandcooldowns.bypass", "Allow to bypass all command cooldowns"),
                new ExternalPluginPermission("essentials.commandcooldowns.bypass.<commandname>", "Allow to bypass a specific command cooldown"),
                new ExternalPluginPermission("essentials.compass", "Allow access to the /compass command.", Collections.singletonList("compass")),
                new ExternalPluginPermission("essentials.condense", "Allow access to the /condense command", Collections.singletonList("condense")),
                new ExternalPluginPermission("essentials.createkit", "Allow access to the /createkit command", Collections.singletonList("createkit")),
                new ExternalPluginPermission("essentials.delkit", "Allow access to the /delkit command", Collections.singletonList("delkit")),
                new ExternalPluginPermission("essentials.kitreset", "Allow access to the /kitreset command", Collections.singletonList("kitreset")),
                new ExternalPluginPermission("essentials.kitreset.others", "Allow to reset other another player's kit cooldown using /kitreset.", Collections.singletonList("kitreset")),
                new ExternalPluginPermission("essentials.customtext", "Allow access to the /customtext command and all aliases.", Collections.singletonList("customtext")),
                new ExternalPluginPermission("essentials.delwarp", "Allow access to the /delwarp command.", Collections.singletonList("delwarp")),
                new ExternalPluginPermission("essentials.depth", "Allow access to the /depth command.", Collections.singletonList("depth")),
                new ExternalPluginPermission("essentials.disposal", "Allow access to the /disposal command", Collections.singletonList("disposal")),
                new ExternalPluginPermission("essentials.eco", "Allow access to the /eco command.", Collections.singletonList("eco")),
                new ExternalPluginPermission("essentials.eco.loan", "Allows the player to have a negative balance.", Collections.singletonList("eco")),
                new ExternalPluginPermission("essentials.enchant", "Allows access to the /enchant command.", Collections.singletonList("enchant")),
                new ExternalPluginPermission("essentials.enchantments.allowunsafe", "If enabled in the config, this permission allows unsafe enchantments.", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.enderchest", "Allow access to the /enderchest command.", Collections.singletonList("enderchest")),
                new ExternalPluginPermission("essentials.enderchest.modify", "Allows you to modify the contents of another players enderchest."),
                new ExternalPluginPermission("essentials.enderchest.others", "Allows you to see the contents of another players enderchest.", Collections.singletonList("enderchest")),
                new ExternalPluginPermission("essentials.essentials", "Allow access to the /essentials command.", Collections.singletonList("essentials")),
                new ExternalPluginPermission("essentials.updatecheck", "Notify players with this permission on join when there is an update available.", Collections.singletonList("essentials")),
                new ExternalPluginPermission("essentials.exp", "Allow access to the /exp command.", Collections.singletonList("exp")),
                new ExternalPluginPermission("essentials.exp.give", "Allows players to give themselves exp.", Collections.singletonList("exp")),
                new ExternalPluginPermission("essentials.exp.give.others", "Allows players to give others exp (if they also have essentials.exp.give).", Collections.singletonList("exp")),
                new ExternalPluginPermission("essentials.exp.others", "Allows players to see another players exp.", Collections.singletonList("exp")),
                new ExternalPluginPermission("essentials.exp.set", "Allows players to set their own exp.", Collections.singletonList("exp")),
                new ExternalPluginPermission("essentials.exp.set.others", "Allows players to change others exp (if they also have essentials.exp.set).", Collections.singletonList("exp")),
                new ExternalPluginPermission("essentials.ext", "Allow access to the /ext command.", Collections.singletonList("ext")),
                new ExternalPluginPermission("essentials.ext.others", "Allow to specify other player in /ext.", Collections.singletonList("ext")),
                new ExternalPluginPermission("essentials.feed", "Allows access to the /feed command.", Collections.singletonList("feed")),
                new ExternalPluginPermission("essentials.feed.cooldown.bypass", "Bypass the feed cooldown. Since build 1452, essentials.commandcooldowns.bypass.feed can be used instead.", Collections.singletonList("feed")),
                new ExternalPluginPermission("essentials.feed.others", "Allows a player to feed another player.", Collections.singletonList("feed")),
                new ExternalPluginPermission("essentials.fireball", "Allow access to the /fireball command. Note: you also need specific permissions for each projectile.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.fireball", "Allow firing regular fireballs.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.small", "Allow firing small fireballs.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.large", "Allow firing large fireballs.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.arrow", "Allow firing arrows.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.skull", "Allow firing wither skulls.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.egg", "Allow firing eggs.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.snowball", "Allow firing frozen fireballs.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.expbottle", "Allow firing experience bottles.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.dragon", "Allow firing Ender Dragon fireballs.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.splashpotion", "Allow firing splash potions.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.lingeringpotion", "Allow firing lingering potions.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.fireball.trident", "Allow firing tridents.", Collections.singletonList("fireball")),
                new ExternalPluginPermission("essentials.firework", "Allow access to the /firework command.", Collections.singletonList("firework")),
                new ExternalPluginPermission("essentials.firework.fire", "Allows a user to 'spawn' a copy of the firework held in their hands.", Collections.singletonList("firework")),
                new ExternalPluginPermission("essentials.firework.multiple", "Allows to spawn multiple firework effects at once", Collections.singletonList("firework")),
                new ExternalPluginPermission("essentials.fly", "Allow access to the /fly command.", Collections.singletonList("fly")),
                new ExternalPluginPermission("essentials.fly.safelogin", "Players with this permission will automatically switch to fly mode if they login whilst floating in the air."),
                new ExternalPluginPermission("essentials.gamemode", "Allow access to the /gamemode command.", Collections.singletonList("gamemode")),
                new ExternalPluginPermission("essentials.gamemode.all", "Allow access to all the gamemodes in the /gamemode command", Collections.singletonList("gamemode")),
                new ExternalPluginPermission("essentials.gamemode.others", "Allows you to change the gamemode of other players.", Collections.singletonList("gamemode")),
                new ExternalPluginPermission("essentials.gc", "Allow access to the /gc command.", Collections.singletonList("gc")),
                new ExternalPluginPermission("essentials.getpos", "Allow access to the /getpos command.", Collections.singletonList("getpos")),
                new ExternalPluginPermission("essentials.getpos.others", "Allow user to get the position of another player.", Collections.singletonList("getpos")),
                new ExternalPluginPermission("essentials.give", "Allow access to the /give command.", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.give.item-all", "If permission-based-item-spawn: Spawn all items", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.give.item-[itemname]", "If permission-based-item-spawn: Spawn [itemname]", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.give.item-[itemid]", "If permission-based-item-spawn: Spawn [itemname]", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.god", "Allow access to the /god command.", Collections.singletonList("god")),
                new ExternalPluginPermission("essentials.god.pvp", "Allows you to attack other players while in god mode.", Collections.singletonList("god")),
                new ExternalPluginPermission("essentials.hat", "Allow access to the /hat command.", Collections.singletonList("hat")),
                new ExternalPluginPermission("essentials.heal", "Allow access to the /heal command.", Collections.singletonList("heal")),
                new ExternalPluginPermission("essentials.heal.cooldown.bypass", "Bypass the heal cooldown. Since build 1452, essentials.commandcooldowns.bypass.heal can be used instead.", Collections.singletonList("heal")),
                new ExternalPluginPermission("essentials.heal.others", "Allows healing another player", Collections.singletonList("heal")),
                new ExternalPluginPermission("essentials.help", "Allow access to the /help command.", Collections.singletonList("help")),
                new ExternalPluginPermission("essentials.helpop", "Allow access to the /helpop command.", Collections.singletonList("helpop")),
                new ExternalPluginPermission("essentials.helpop.receive", "Allows you to see Helpop messages", Collections.singletonList("helpop")),
                new ExternalPluginPermission("essentials.home.compass", "Point the player's compass at their first home. compass-towards-home-perm needs to be enabled in the configuration.", Collections.singletonList("home")),
                new ExternalPluginPermission("essentials.home.bed", "Allow access to the vanilla bed home.", Collections.singletonList("home")),
                new ExternalPluginPermission("essentials.home.others", "Allows you to teleport to homes of other players", Collections.singletonList("home")),
                new ExternalPluginPermission("essentials.ice", "Allow access to the /ice command.", Collections.singletonList("ice")),
                new ExternalPluginPermission("essentials.ice.others", "Allow to use the /ice command on other players.", Collections.singletonList("ice")),
                new ExternalPluginPermission("essentials.ignore", "Allow access to the /ignore command.", Collections.singletonList("ignore")),
                new ExternalPluginPermission("essentials.info", "Allow access to the /info command.", Collections.singletonList("info")),
                new ExternalPluginPermission("essentials.invsee", "Allow access to the /invsee command.", Collections.singletonList("invsee")),
                new ExternalPluginPermission("essentials.invsee.equip", "Allow access to see someones equiped armor slots in /invsee <name> [armor]", Collections.singletonList("invsee")),
                new ExternalPluginPermission("essentials.invsee.modify", "Players can modify the other players inventory (remove/add items).", Collections.singletonList("invsee")),
                new ExternalPluginPermission("essentials.invsee.preventmodify", "Prevents other players from modifying the players inventory.", Collections.singletonList("invsee")),
                new ExternalPluginPermission("essentials.item", "Allow access to the /item command.", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.itemlore", "Allow access to the /itemlore command.", Collections.singletonList("itemlore")),
                new ExternalPluginPermission("essentials.itemdb", "Allows access to the /itemdb command.", Collections.singletonList("itemdb")),
                new ExternalPluginPermission("essentials.itemname", "Allows access to the /itemname command.", Collections.singletonList("itemname")),
                new ExternalPluginPermission("essentials.itemname.<effect>", "Gives access to use <effect> in the /itemname command. <effect> examples: bold, reset, gold, dark_red, *", Collections.singletonList("itemname")),
                new ExternalPluginPermission("essentials.itemname.prevent-type.<material_name>", "Prevents the material from being used with the /itemname command", Collections.singletonList("itemname")),
                new ExternalPluginPermission("essentials.itemspawn.exempt", "Allows spawning of items on the spawn blacklist.", Collections.singletonList("more")),
                new ExternalPluginPermission("essentials.jail.exempt", "Prevents a specified group or player from being jailed", Collections.singletonList("togglejail")),
                new ExternalPluginPermission("essentials.jails", "Allow access to the /jails command.", Collections.singletonList("jails")),
                new ExternalPluginPermission("essentials.deljail", "Allow access to the /deljail command.", Collections.singletonList("deljail")),
                new ExternalPluginPermission("essentials.jail.allow-break", "Allow breaking blocks whilst jailed. (Might also want to add essentials.jail.allow-block-damage)", Collections.singletonList("jail")),
                new ExternalPluginPermission("essentials.jail.allow-place", "Allow placing blocks whilst jailed", Collections.singletonList("jail")),
                new ExternalPluginPermission("essentials.jail.allow-block-damage", "Allow damaging blocks whilst jailed. (Might also want to add essentials.jail.allow-break)", Collections.singletonList("jail")),
                new ExternalPluginPermission("essentials.jail.allow-interact", "Allow interacting whilst jailed", Collections.singletonList("jail")),
                new ExternalPluginPermission("essentials.joinfullserver", "Player can join when the server is full."),
                new ExternalPluginPermission("essentials.jump", "Allow access to the /jump command.", Collections.singletonList("jump")),
                new ExternalPluginPermission("essentials.jump.lock", "Allow access to the /jump lock command", Collections.singletonList("jump")),
                new ExternalPluginPermission("essentials.keepxp", "Allows the user to keep their exp on death, instead of dropping it.", Collections.singletonList("back")),
                new ExternalPluginPermission("essentials.kick", "Allow access to the /kick command.", Collections.singletonList("kick")),
                new ExternalPluginPermission("essentials.kick.exempt", "Prevents the player from being kicked.", Collections.singletonList("kick")),
                new ExternalPluginPermission("essentials.kick.notify", "User sees a notification when a user is kicked.", Collections.singletonList("kick")),
                new ExternalPluginPermission("essentials.kickall", "Allow access to the /kickall command.", Collections.singletonList("kickall")),
                new ExternalPluginPermission("essentials.kickall.exempt", "Be exempt from the /kickall command.", Collections.singletonList("kickall")),
                new ExternalPluginPermission("essentials.kill", "Allow access to the /kill command.", Collections.singletonList("kill")),
                new ExternalPluginPermission("essentials.kill.exempt", "Prevents the player from being killed.", Collections.singletonList("kill")),
                new ExternalPluginPermission("essentials.kill.force", "Force player death, even if event is cancelled.", Collections.singletonList("kill")),
                new ExternalPluginPermission("essentials.kit", "Allow access to the /kit command.", Collections.singletonList("kit")),
                new ExternalPluginPermission("essentials.kit.exemptdelay", "Exempts you from the kit delay feature, this affects signs as well as command.", Collections.singletonList("kit")),
                new ExternalPluginPermission("essentials.kit.others", "Allows spawning of kits on other players.", Collections.singletonList("kit")),
                new ExternalPluginPermission("essentials.kittycannon", "Allow access to the /kittycannon command", Collections.singletonList("kittycannon")),
                new ExternalPluginPermission("essentials.beezooka", "Allow access to the /beezooka command", Collections.singletonList("beezooka")),
                new ExternalPluginPermission("essentials.lightning", "Allow access to the /lightning command.", Collections.singletonList("lightning")),
                new ExternalPluginPermission("essentials.lightning.others", "Allows use of /lightning [playername]", Collections.singletonList("lightning")),
                new ExternalPluginPermission("essentials.list", "Allow access to the /list command.", Collections.singletonList("list")),
                new ExternalPluginPermission("essentials.list.hidden", "Show hidden users", Collections.singletonList("list")),
                new ExternalPluginPermission("essentials.mail", "Allow access to the /mail command.", Collections.singletonList("mail")),
                new ExternalPluginPermission("essentials.mail.send", "Send mail", Collections.singletonList("mail")),
                new ExternalPluginPermission("essentials.mail.sendall", "Allows sending mail to all players at the same time", Collections.singletonList("mail")),
                new ExternalPluginPermission("essentials.mail.sendtemp", "Allows to send self-destructing mail.", Collections.singletonList("mail")),
                new ExternalPluginPermission("essentials.me", "Allow access to the /me command.", Collections.singletonList("me")),
                new ExternalPluginPermission("essentials.more", "Allows access to the /more command.", Collections.singletonList("more")),
                new ExternalPluginPermission("essentials.motd", "User sees MOTD on connect, and can use the command.", Collections.singletonList("motd")),
                new ExternalPluginPermission("essentials.msg", "Allow access to the /msg command.", Collections.singletonList("msg")),
                new ExternalPluginPermission("essentials.msg.color", "Allows using color codes in /msg command.", Collections.singletonList("msg")),
                new ExternalPluginPermission("essentials.msg.rgb", "Allows using rgb colors in /msg command.", Collections.singletonList("msg")),
                new ExternalPluginPermission("essentials.msg.magic", "Allows to use the matrix/magic color in the /msg command.", Collections.singletonList("msg")),
                new ExternalPluginPermission("essentials.msg.url", "Allows using urls in the /msg command.", Collections.singletonList("msg")),
                new ExternalPluginPermission("essentials.msg.format", "Allows to use formatting in the /msg command.", Collections.singletonList("msg")),
                new ExternalPluginPermission("essentials.msg.multiple", "This allows you to message multiple users in a single command.", Collections.singletonList("msg")),
                new ExternalPluginPermission("essentials.msgtoggle", "Allows access to the /msgtoggle command", Collections.singletonList("msgtoggle")),
                new ExternalPluginPermission("essentials.mute", "Allow access to the /mute command.", Collections.singletonList("mute")),
                new ExternalPluginPermission("essentials.mute.exempt", "Prevents a specified group or player from being muted", Collections.singletonList("mute")),
                new ExternalPluginPermission("essentials.mute.unlimited", "Allow overriding the max-mute-time set in the config", Collections.singletonList("mute")),
                new ExternalPluginPermission("essentials.mute.offline", "Allows muting of players who are offline. This may allow you to mute exempt players.", Collections.singletonList("mute")),
                new ExternalPluginPermission("essentials.near", "Allow access to the /near command.", Collections.singletonList("near")),
                new ExternalPluginPermission("essentials.near.maxexempt", "Allows bypassing the radius limit.", Collections.singletonList("near")),
                new ExternalPluginPermission("essentials.near.others", "Allows using the near command on another player.", Collections.singletonList("near")),
                new ExternalPluginPermission("essentials.near.exclude", "Player gets excluded from /near lookup.", Collections.singletonList("near")),
                new ExternalPluginPermission("essentials.nick", "Allow access to the /nick command.", Collections.singletonList("nick")),
                new ExternalPluginPermission("essentials.nick.<color>", "Allows you to color your /nick in <color> using color codes.", Collections.singletonList("nick")),
                new ExternalPluginPermission("essentials.nick.blacklist.bypass", "Allow access to bypass the /nick blacklist.", Collections.singletonList("nick")),
                new ExternalPluginPermission("essentials.nick.changecolors", "Allow to **only** change your nickname's colors (And not the name itself)", Collections.singletonList("nick")),
                new ExternalPluginPermission("essentials.nick.changecolors.bypass", "Allows to bypass checking if only nickname colors were changed, thus also allowing to change letters.", Collections.singletonList("nick")),
                new ExternalPluginPermission("essentials.nick.rgb", "Gives permission to use hex colors in the /nick command using the &#RRGGBB format.", Collections.singletonList("nick")),
                new ExternalPluginPermission("essentials.nick.others", "Gives you permission to give other players a nick name", Collections.singletonList("nick")),
                new ExternalPluginPermission("essentials.nocommandcost.all", "Removes the command cost of all commands."),
                new ExternalPluginPermission("essentials.nuke", "Allow access to the /nuke command.", Collections.singletonList("nuke")),
                new ExternalPluginPermission("essentials.oversizedstacks", "Allows spawning of oversized stacks.", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.pay", "Allow access to the /pay command.", Collections.singletonList("pay")),
                new ExternalPluginPermission("essentials.pay.multiple", "This allows you to pay multiple users in a single command.", Collections.singletonList("pay")),
                new ExternalPluginPermission("essentials.pay.offline", "This allows you to pay offline players.", Collections.singletonList("pay")),
                new ExternalPluginPermission("essentials.payconfirmtoggle", "Allow access to the /payconfirmtoggle command.", Collections.singletonList("payconfirmtoggle")),
                new ExternalPluginPermission("essentials.paytoggle", "Allow access to the /paytoggle command.", Collections.singletonList("paytoggle")),
                new ExternalPluginPermission("essentials.ping", "Allow access to the /ping command.", Collections.singletonList("ping")),
                new ExternalPluginPermission("essentials.potion.[potionName]", "Allow access to the /potion [potionName] command ", Collections.singletonList("potion")),
                new ExternalPluginPermission("essentials.potion.apply", "Allow access to the /potion apply command", Collections.singletonList("potion")),
                new ExternalPluginPermission("essentials.powertool", "Allow access to the /powertool command.", Collections.singletonList("powertool")),
                new ExternalPluginPermission("essentials.powertool.append", "Allows adding multiple commands to a single powertool.", Collections.singletonList("powertool")),
                new ExternalPluginPermission("essentials.powertooltoggle", "Allow access to the /powertooltoggle command.", Collections.singletonList("powertooltoggle")),
                new ExternalPluginPermission("essentials.ptime", "Allow access to the /ptime command.", Collections.singletonList("ptime")),
                new ExternalPluginPermission("essentials.ptime.others", "Allows you to change the time of another online player.", Collections.singletonList("ptime")),
                new ExternalPluginPermission("essentials.pvpdelay.exempt", "Exempts players from the 'pvp delay' option in the config file."),
                new ExternalPluginPermission("essentials.pweather", "Allow access to the /pweather command", Collections.singletonList("pweather")),
                new ExternalPluginPermission("essentials.pweather.others", "Allow to change the pweather of someone else", Collections.singletonList("pweather")),
                new ExternalPluginPermission("essentials.msg", "Allow access to the /r command", Collections.singletonList("r")),
                new ExternalPluginPermission("essentials.rtoggle", "Allows access to toggle replying to last message recipient", Collections.singletonList("rtoggle")),
                new ExternalPluginPermission("essentials.realname", "Allow access to the /realname command.", Collections.singletonList("realname")),
                new ExternalPluginPermission("essentials.recipe", "Allow access to the /recipe command.", Collections.singletonList("recipe")),
                new ExternalPluginPermission("essentials.remove", "Allow access to the /remove command.", Collections.singletonList("remove")),
                new ExternalPluginPermission("essentials.repair", "Allow access to the /repair command.", Collections.singletonList("repair")),
                new ExternalPluginPermission("essentials.repair.all", "Unlock the /repair all ability", Collections.singletonList("repair")),
                new ExternalPluginPermission("essentials.repair.armor", "Repair all also repairs equipped armor.", Collections.singletonList("repair")),
                new ExternalPluginPermission("essentials.repair.enchanted", "Repairing of enchanted items.", Collections.singletonList("repair")),
                new ExternalPluginPermission("essentials.rest", "Allow access to the /rest command.", Collections.singletonList("rest")),
                new ExternalPluginPermission("essentials.rest.others", "Allow to specify other player in /rest.", Collections.singletonList("rest")),
                new ExternalPluginPermission("essentials.rules", "Allow access to the /rules command.", Collections.singletonList("rules")),
                new ExternalPluginPermission("essentials.seen", "Allow access to the /seen command.", Collections.singletonList("seen")),
                new ExternalPluginPermission("essentials.seen.banreason", "Allows the user to see why a user is banned.", Collections.singletonList("seen")),
                new ExternalPluginPermission("essentials.seen.ip", "Allow to see someone's ip-address in /seen", Collections.singletonList("seen")),
                new ExternalPluginPermission("essentials.seen.uuid", "Allow to see someone's uuid in /seen", Collections.singletonList("seen")),
                new ExternalPluginPermission("essentials.seen.ipsearch", "Allows the user to search IPs for username matches.", Collections.singletonList("seen")),
                new ExternalPluginPermission("essentials.seen.location", "Allow to see someone's location in /seen", Collections.singletonList("seen")),
                new ExternalPluginPermission("essentials.seen.alts", "Allows the user to see accounts with the same IP in /seen", Collections.singletonList("alts")),
                new ExternalPluginPermission("essentials.sell", "Allow access to the /sell command.", Collections.singletonList("sell")),
                new ExternalPluginPermission("essentials.sell.bulk", "Allow bulk selling of items", Collections.singletonList("sell")),
                new ExternalPluginPermission("essentials.sell.hand", "Allow selling of items from your hand", Collections.singletonList("sell")),
                new ExternalPluginPermission("essentials.home", "Allows access to the /home command", Collections.singletonList("home")),
                new ExternalPluginPermission("essentials.sethome", "Allow access to the /sethome command.", Collections.singletonList("sethome")),
                new ExternalPluginPermission("essentials.sethome.bed", "Allows the player to right click a bed during daytime to update their 'bed' home."),
                new ExternalPluginPermission("essentials.sethome.multiple", "Allows player to have multiple homes, or create named homes.  Required for 2+ homes."),
                new ExternalPluginPermission("essentials.sethome.multiple.[set name]", "Raise the multiple home limit to a setting defined in the config file.", Collections.singletonList("sethome")),
                new ExternalPluginPermission("essentials.sethome.multiple.unlimited", "Removes the cap on the number of homes people are allowed (if they have multiple homes).", Collections.singletonList("home")),
                new ExternalPluginPermission("essentials.sethome.others", "Allows you to change another users home location.", Collections.singletonList("sethome")),
                new ExternalPluginPermission("essentials.delhome", "Allow access to the /delhome command.", Collections.singletonList("delhome")),
                new ExternalPluginPermission("essentials.delhome.others", "Allows you to delete the homes of other players.", Collections.singletonList("delhome")),
                new ExternalPluginPermission("essentials.setjail", "Allow access to the /setjail command.", Collections.singletonList("setjail")),
                new ExternalPluginPermission("essentials.jail.notify", "Players with this permission will be notified when someone is jailed.", Collections.singletonList("jail")),
                new ExternalPluginPermission("essentials.setwarp", "Allow access to the /setwarp command.", Collections.singletonList("setwarp")),
                new ExternalPluginPermission("essentials.setworth", "Allow access to the /setworth command.", Collections.singletonList("setworth")),
                new ExternalPluginPermission("essentials.showkit", "Allow access to the /showkit command.", Collections.singletonList("showkit")),
                new ExternalPluginPermission("essentials.signs.enchant.allowunsafe", "Allows using [enchant] signs to perform unsafe enchantments"),
                new ExternalPluginPermission("essentials.signs.protection.override", "Used to override any protections. Typically given to mods &amp; admins"),
                new ExternalPluginPermission("essentials.signs.trade.override", "Used to override the creator only protection on trade signs. Typically given to mods &amp; admins"),
                new ExternalPluginPermission("essentials.signs.trade.override.collect", "Allow collecting of protected trade signs"),
                new ExternalPluginPermission("essentials.silentjoin", "Allow to join silently"),
                new ExternalPluginPermission("essentials.silentjoin.vanish", "Allow to join silently, and get put in vanish mode"),
                new ExternalPluginPermission("essentials.silentquit", "Suppress leave/quit messages for users with this permission."),
                new ExternalPluginPermission("essentials.skull", "Allow access to the /skull command.", Collections.singletonList("skull")),
                new ExternalPluginPermission("essentials.skull.modify", "Allow changing the owner of an existing player skull.", Collections.singletonList("skull")),
                new ExternalPluginPermission("essentials.skull.others", "Allow creating skulls belonging to other players.", Collections.singletonList("skull")),
                new ExternalPluginPermission("essentials.skull.spawn", "Allows the spawning of a skull, default if the player isn't holding a skull.", Collections.singletonList("skull")),
                new ExternalPluginPermission("essentials.sleepingignored", "User isn't required to be sleeping, for time to be reset."),
                new ExternalPluginPermission("essentials.socialspy", "Allow access to the /socialspy command.", Collections.singletonList("socialspy")),
                new ExternalPluginPermission("essentials.spawner", "Allow access to the /spawner command.", Collections.singletonList("spawner")),
                new ExternalPluginPermission("essentials.spawner.delay", "Allow access to adjust delay in /spawner command.", Collections.singletonList("spawner")),
                new ExternalPluginPermission("essentials.spawnmob", "Allow access to the /spawnmob command.", Collections.singletonList("spawnmob")),
                new ExternalPluginPermission("essentials.spawnmob.stack", "Allows the spawning of stacked mobs.", Collections.singletonList("spawnmob")),
                new ExternalPluginPermission("essentials.speed", "Allow access to the /speed command.", Collections.singletonList("speed")),
                new ExternalPluginPermission("essentials.speed.bypass", "Allows you to bypass the speed limits set in the config.yml", Collections.singletonList("speed")),
                new ExternalPluginPermission("essentials.speed.fly", "This permission will allow a player to change fly speed only.", Collections.singletonList("speed")),
                new ExternalPluginPermission("essentials.speed.others", "Allows you to modify the speed of other players.", Collections.singletonList("speed")),
                new ExternalPluginPermission("essentials.speed.walk", "This permission will allow a player to change walk speed only.", Collections.singletonList("speed")),
                new ExternalPluginPermission("essentials.sudo", "Allow access to the /sudo command.", Collections.singletonList("sudo")),
                new ExternalPluginPermission("essentials.sudo.exempt", "Prevents the holder from being sudo'ed by another user.", Collections.singletonList("sudo")),
                new ExternalPluginPermission("essentials.sudo.multiple", "Allow access to the /sudo command for multiple people.", Collections.singletonList("sudo")),
                new ExternalPluginPermission("essentials.suicide", "Allow access to the /suicide command.", Collections.singletonList("suicide")),
                new ExternalPluginPermission("essentials.teleport.cooldown.bypass.back", "Allow to bypass the /back command cooldown. Since build 1452, essentials.commandcooldowns.bypass.back can be used instead."),
                new ExternalPluginPermission("essentials.teleport.cooldown.bypass.tpa", "Allow to bypass the /tpa command cooldown. Since build 1452, essentials.commandcooldowns.bypass.tpa can be used instead."),
                new ExternalPluginPermission("essentials.teleport.timer.bypass", "Bypass the teleport delay"),
                new ExternalPluginPermission("essentials.teleport.timer.move", "Allows players to move while waiting for teleport."),
                new ExternalPluginPermission("essentials.tempban", "Allow access to the /tempban command.", Collections.singletonList("tempban")),
                new ExternalPluginPermission("essentials.tempban.exempt", "Prevents a specified group or player from being tempbanned", Collections.singletonList("tempban")),
                new ExternalPluginPermission("essentials.tempban.offline", "Allows temp-banning of players who are offline.  This may allow you to ban exempt players.", Collections.singletonList("tempban")),
                new ExternalPluginPermission("essentials.tempban.unlimited", "Allows bypassing config file max ban time limit.", Collections.singletonList("tempban")),
                new ExternalPluginPermission("essentials.tempbanip", "Allow access to the /tempbanip command.", Collections.singletonList("tempbanip")),
                new ExternalPluginPermission("essentials.thunder", "Allow access to the /thunder command.", Collections.singletonList("thunder")),
                new ExternalPluginPermission("essentials.time", "Allow access to the /time command.", Collections.singletonList("time")),
                new ExternalPluginPermission("essentials.time.set", "User is allowed to change the time of the world.", Collections.singletonList("time")),
                new ExternalPluginPermission("essentials.time.world.all", "Allow changing time of all worlds", Collections.singletonList("time")),
                new ExternalPluginPermission("essentials.togglejail", "Allow access to the /togglejail command.", Collections.singletonList("togglejail")),
                new ExternalPluginPermission("essentials.togglejail.offline", "Allows jailing of players who are offline.  This may allow you to jail exempt players.", Collections.singletonList("togglejail")),
                new ExternalPluginPermission("essentials.top", "Allow access to the /top command.", Collections.singletonList("top")),
                new ExternalPluginPermission("essentials.tp", "Allow access to the /tp command.", Collections.singletonList("tp")),
                new ExternalPluginPermission("essentials.tpauto", "Allow access to the /tpauto command.", Collections.singletonList("tpauto")),
                new ExternalPluginPermission("essentials.tp.others", "Allow players to teleport another player.", Collections.singletonList("tpo")),
                new ExternalPluginPermission("essentials.tp.position", "Allow to teleport to an exact location", Collections.singletonList("tp")),
                new ExternalPluginPermission("essentials.tpoffline", "Allow teleporting to a player's logout location using /tpoffline", Collections.singletonList("tpoffline")),
                new ExternalPluginPermission("essentials.tpa", "Allow access to the /tpa command.", Collections.singletonList("tpa")),
                new ExternalPluginPermission("essentials.tpaall", "Allow access to the /tpaall command.", Collections.singletonList("tpaall")),
                new ExternalPluginPermission("essentials.tpacancel", "Allow access to the /tpacancel command.", Collections.singletonList("tpacancel")),
                new ExternalPluginPermission("essentials.tpaccept", "Allow access to the /tpaccept command.", Collections.singletonList("tpaccept")),
                new ExternalPluginPermission("essentials.tpahere", "Allow access to the /tpahere command.", Collections.singletonList("tpahere")),
                new ExternalPluginPermission("essentials.tpall", "Allow access to the /tpall command.", Collections.singletonList("tpall")),
                new ExternalPluginPermission("essentials.tpdeny", "Allow access to the /tpdeny command.", Collections.singletonList("tpdeny")),
                new ExternalPluginPermission("essentials.tphere", "Allow access to the /tphere command.", Collections.singletonList("tphere")),
                new ExternalPluginPermission("essentials.tpo", "Allow access to the /tpo command.", Collections.singletonList("tpo")),
                new ExternalPluginPermission("essentials.tpohere", "Allow access to the /tpohere command.", Collections.singletonList("tpohere")),
                new ExternalPluginPermission("essentials.tppos", "Allow access to the /tppos command.", Collections.singletonList("tppos")),
                new ExternalPluginPermission("essentials.tptoggle", "Allow access to the /tptoggle command.", Collections.singletonList("tptoggle")),
                new ExternalPluginPermission("essentials.tpr", "Allow access to the /tpr command.", Collections.singletonList("tpr")),
                new ExternalPluginPermission("essentials.settpr", "Allow access to the /settpr command.", Collections.singletonList("settpr")),
                new ExternalPluginPermission("essentials.tree", "Allow access to the /tree command.", Collections.singletonList("tree")),
                new ExternalPluginPermission("essentials.unlimited", "Allow access to the /unlimited command.", Collections.singletonList("unlimited")),
                new ExternalPluginPermission("essentials.unlimited.item-all", "Allows the player to recieve an unlimited stack of any item.", Collections.singletonList("unlimited")),
                new ExternalPluginPermission("essentials.unlimited.item-bucket", "Allows the player to recieve an unlimited use of empty/lava/water buckets.", Collections.singletonList("unlimited")),
                new ExternalPluginPermission("essentials.unlimited.others", "Allows the player to gift/remove another player with an unlimited stack.", Collections.singletonList("unlimited")),
                new ExternalPluginPermission("essentials.vanish", "Allow access to the /vanish command.", Collections.singletonList("vanish")),
                new ExternalPluginPermission("essentials.vanish.pvp", "Allows players who are vanished to attack other players.", Collections.singletonList("vanish")),
                new ExternalPluginPermission("essentials.vanish.see", "Allows you to see a vanished player.", Collections.singletonList("vanish")),
                new ExternalPluginPermission("essentials.version", "Allow access to the /essentials version command", Collections.singletonList("essentials")),
                new ExternalPluginPermission("essentials.warp", "Allow access to the /warp command.", Collections.singletonList("warp")),
                new ExternalPluginPermission("essentials.warp.list", "Specifies whether you can view warp list with /warp.", Collections.singletonList("warp")),
                new ExternalPluginPermission("essentials.warp.otherplayers", "Allows warping another player.", Collections.singletonList("warp")),
                new ExternalPluginPermission("essentials.warp.others", "Allows warping another player.", Collections.singletonList("warp")),
                new ExternalPluginPermission("essentials.warpinfo", "Allow access to the /warpinfo command.", Collections.singletonList("warpinfo")),
                new ExternalPluginPermission("essentials.weather", "Allow access to the /weather command.", Collections.singletonList("weather")),
                new ExternalPluginPermission("essentials.whois", "Allow access to the /whois command.", Collections.singletonList("whois")),
                new ExternalPluginPermission("essentials.workbench", "Allow access to the /workbench command.", Collections.singletonList("workbench")),
                new ExternalPluginPermission("essentials.anvil", "Allow access to the /anvil command.", Collections.singletonList("anvil")),
                new ExternalPluginPermission("essentials.cartographytable", "Allow access to the /cartographytable command.", Collections.singletonList("cartographytable")),
                new ExternalPluginPermission("essentials.grindstone", "Allow access to the /grindstone command.", Collections.singletonList("grindstone")),
                new ExternalPluginPermission("essentials.loom", "Allow access to the /loom command.", Collections.singletonList("loom")),
                new ExternalPluginPermission("essentials.smithingtable", "Allow access to the /smithingtable command.", Collections.singletonList("smithingtable")),
                new ExternalPluginPermission("essentials.stonecutter", "Allow access to the /stonecutter command.", Collections.singletonList("stonecutter")),
                new ExternalPluginPermission("essentials.world", "Allow access to the /world command.", Collections.singletonList("world")),
                new ExternalPluginPermission("essentials.worth", "Allow access to the /worth command.", Collections.singletonList("worth")),
                new ExternalPluginPermission("essentials.fly.others", "Allow executing the /fly command for someone else.", Collections.singletonList("fly")),
                new ExternalPluginPermission("essentials.god.others", "Allow executing the /god command for someone else.", Collections.singletonList("god")),
                new ExternalPluginPermission("essentials.msgtoggle.others", "Allow executing the /msgtoggle command for someone else.", Collections.singletonList("msgtoggle")),
                new ExternalPluginPermission("essentials.socialspy.others", "Allow executing the /socialspy command for someone else.", Collections.singletonList("socialspy")),
                new ExternalPluginPermission("essentials.tptoggle.others", "Allow executing the /tptoggle command for someone else.", Collections.singletonList("tptoggle")),
                new ExternalPluginPermission("essentials.vanish.others", "Allow executing the /vanish command for someone else.", Collections.singletonList("vanish")),
                new ExternalPluginPermission("essentials.seen.extra", "Allow to see someone's ip-address and location in /seen"),
                new ExternalPluginPermission("essentials.nocommandcost.[command]", "Removes the command cost of a given command."),
                new ExternalPluginPermission("essentials.signs.break.balance", "Controls who can break balance signs."),
                new ExternalPluginPermission("essentials.signs.break.buy", "Controls who can break buy signs."),
                new ExternalPluginPermission("essentials.signs.break.disposal", "Controls who can break disposal signs."),
                new ExternalPluginPermission("essentials.signs.break.enchant", "Controls who can break enchant signs."),
                new ExternalPluginPermission("essentials.signs.break.free", "Controls who can break free signs."),
                new ExternalPluginPermission("essentials.signs.break.gamemode", "Controls who can break gamemode signs."),
                new ExternalPluginPermission("essentials.signs.break.heal", "Controls who can break heal signs."),
                new ExternalPluginPermission("essentials.signs.break.info", "Controls who can break info signs."),
                new ExternalPluginPermission("essentials.signs.break.kit", "Controls who can break kit signs."),
                new ExternalPluginPermission("essentials.signs.break.mail", "Controls who can break a mail sign."),
                new ExternalPluginPermission("essentials.signs.break.protection", "Controls who can break a protection sign. Typically given to everybody."),
                new ExternalPluginPermission("essentials.signs.break.repair", "Controls who can break repair signs."),
                new ExternalPluginPermission("essentials.signs.break.sell", "Controls who can break sell signs."),
                new ExternalPluginPermission("essentials.signs.break.spawnmob", "Controls who can break spawnmob signs."),
                new ExternalPluginPermission("essentials.signs.break.time", "Controls who can break time signs."),
                new ExternalPluginPermission("essentials.signs.break.trade", "Controls who can break trade signs."),
                new ExternalPluginPermission("essentials.signs.break.warp", "Controls who can break warp signs."),
                new ExternalPluginPermission("essentials.signs.break.weather", "Controls who can break weather signs."),
                new ExternalPluginPermission("essentials.signs.color", "This allows you to color your signs using color codes."),
                new ExternalPluginPermission("essentials.signs.rgb", "This allows you to color your signs using hex color formatting, &#RRGGBB."),
                new ExternalPluginPermission("essentials.signs.create.balance", "Controls who can create balance signs."),
                new ExternalPluginPermission("essentials.signs.create.buy", "Controls who can create buy signs."),
                new ExternalPluginPermission("essentials.signs.create.disposal", "Controls who can create disposal signs."),
                new ExternalPluginPermission("essentials.signs.create.enchant", "Controls who can create enchant signs."),
                new ExternalPluginPermission("essentials.signs.create.free", "Controls who can create free signs."),
                new ExternalPluginPermission("essentials.signs.create.gamemode", "Controls who can create gamemode signs."),
                new ExternalPluginPermission("essentials.signs.create.heal", "Controls who can create heal signs."),
                new ExternalPluginPermission("essentials.signs.create.info", "Controls who can create info signs."),
                new ExternalPluginPermission("essentials.signs.create.kit", "Controls who can create kit signs."),
                new ExternalPluginPermission("essentials.signs.create.mail", "Controls who can create a mail sign."),
                new ExternalPluginPermission("essentials.signs.create.protection", "Controls who can create a protection sign."),
                new ExternalPluginPermission("essentials.signs.create.repair", "Controls who can create repair signs."),
                new ExternalPluginPermission("essentials.signs.create.sell", "Controls who can create sell signs."),
                new ExternalPluginPermission("essentials.signs.create.spawnmob", "Controls who can create spawnmob signs."),
                new ExternalPluginPermission("essentials.signs.create.time", "Controls who can create time signs."),
                new ExternalPluginPermission("essentials.signs.create.trade", "Controls who can create trade signs."),
                new ExternalPluginPermission("essentials.signs.create.warp", "Controls who can create warp signs."),
                new ExternalPluginPermission("essentials.signs.create.weather", "Controls who can create weather signs."),
                new ExternalPluginPermission("essentials.signs.format", "This allows you to format your signs using format codes."),
                new ExternalPluginPermission("essentials.signs.magic", "This allows you to use the matrix/magic color in your signs."),
                new ExternalPluginPermission("essentials.signs.use.balance", "Controls who can use balance signs."),
                new ExternalPluginPermission("essentials.signs.use.buy", "Controls who can use buy signs."),
                new ExternalPluginPermission("essentials.signs.use.disposal", "Controls who can use disposal signs."),
                new ExternalPluginPermission("essentials.signs.use.enchant", "Controls who can use enchant signs."),
                new ExternalPluginPermission("essentials.signs.use.free", "Controls who can use free signs."),
                new ExternalPluginPermission("essentials.signs.use.gamemode", "Controls who can use gamemode signs."),
                new ExternalPluginPermission("essentials.signs.use.heal", "Controls who can use heal signs."),
                new ExternalPluginPermission("essentials.signs.use.info", "Controls who can use info signs."),
                new ExternalPluginPermission("essentials.signs.use.kit", "Controls who can use kit signs."),
                new ExternalPluginPermission("essentials.signs.use.mail", "Controls who can use a mail sign."),
                new ExternalPluginPermission("essentials.signs.use.protection", "Controls who can use a protection sign. Typically given to everybody."),
                new ExternalPluginPermission("essentials.signs.use.repair", "Controls who can use repair signs."),
                new ExternalPluginPermission("essentials.signs.use.sell", "Controls who can use sell signs."),
                new ExternalPluginPermission("essentials.signs.use.spawnmob", "Controls who can use spawnmob signs."),
                new ExternalPluginPermission("essentials.signs.use.time", "Controls who can use time signs."),
                new ExternalPluginPermission("essentials.signs.use.trade", "Controls who can use trade signs."),
                new ExternalPluginPermission("essentials.signs.use.warp", "Controls who can use warp signs."),
                new ExternalPluginPermission("essentials.signs.use.weather", "Controls who can use weather signs."),
                new ExternalPluginPermission("essentials.editsign", "Allows access to the editsign command", Collections.singletonList("editsign")),
                new ExternalPluginPermission("essentials.editsign.unlimited", "Allows access to exceed the 15-character-per-line limit", Collections.singletonList("editsign")),
                new ExternalPluginPermission("essentials.editsign.rgb", "Allows access to hex colors in the /editsign command using the &#RRGGBB format", Collections.singletonList("editsign")),
                new ExternalPluginPermission("essentials.editsign.color", "This allows you to use any color code within the /editsign command, NOT including hex colors (&#RRGGBB).", Collections.singletonList("editsign")),
                new ExternalPluginPermission("essentials.editsign.<color>", "Allows you to /editsign in <color> using color codes.", Collections.singletonList("editsign")),
                new ExternalPluginPermission("essentials.itemspawn.meta-chapter-[chapter]", "Allow access to the Allows spawning of specific books only, from book.txt./give command.", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.help.[pluginname]", "Manually adds the commands from a plugin to this group's /help. Name is all lowercase.", Collections.singletonList("help")),
                new ExternalPluginPermission("essentials.help.[pluginname].[command]", "Manually adds a command from a plugin to this group's /help. Name is all lowercase.", Collections.singletonList("help")),
                new ExternalPluginPermission("essentials.jail.allow.<command>", "Allows essentials commands to be used while jailed (requires regular perm).", Collections.singletonList("togglejail")),
                new ExternalPluginPermission("essentials.kits.*", "Allows access to all created kits", Collections.singletonList("kit")),
                new ExternalPluginPermission("essentials.kits.[kitname]", "Give access to a single kit, where [kitname] is the name of an existing kit.", Collections.singletonList("kit")),
                new ExternalPluginPermission("essentials.spawner.*", "Allows setting a spawner to any mob type", Collections.singletonList("spawner")),
                new ExternalPluginPermission("essentials.spawner.[mob]", "Allows setting a spawner to a specific mob type", Collections.singletonList("spawner")),
                new ExternalPluginPermission("essentials.spawner.delay", "Allows setting the delay of a spawner.", Collections.singletonList("spawner")),
                new ExternalPluginPermission("essentials.spawnerconvert.*", "Allows placing a spawner of any type", Collections.singletonList("spawner")),
                new ExternalPluginPermission("essentials.spawnerconvert.[mob]", "Allows placing a spawner of a specific mob type", Collections.singletonList("spawner")),
                new ExternalPluginPermission("essentials.spawnmob.*", "Allow the spawning of all mobs", Collections.singletonList("spawnmob")),
                new ExternalPluginPermission("essentials.spawnmob.[mob]", "Allow access to spawn a specific mob", Collections.singletonList("spawnmob")),
                new ExternalPluginPermission("essentials.unlimited.item-[itemid]", "Allows the player to recieve an unlimited stack of [itemid]", Collections.singletonList("unlimited")),
                new ExternalPluginPermission("essentials.unlimited.item-[itemname]", "Allows the player to recieve an unlimited stack of [itemname]", Collections.singletonList("unlimited")),
                new ExternalPluginPermission("essentials.warp.overwrite.*", "Allows overwriting of all existing warps.", Collections.singletonList("setwarp")),
                new ExternalPluginPermission("essentials.warp.overwrite.[warpname]", "Allows overwriting of existing warps.", Collections.singletonList("setwarp")),
                new ExternalPluginPermission("essentials.warps.*", "Allows access to all warps.", Collections.singletonList("warp")),
                new ExternalPluginPermission("essentials.warps.[warpname]", "If you have per-warp-permission set to true in the config.yml then you can limit what warps players can use. This also controls what players would see with /warp and /warpinfo.", Collections.singletonList("warp")),
                new ExternalPluginPermission("essentials.worlds.<worldname>", "Allows players access to a specific world.", Collections.singletonList("back")),
                new ExternalPluginPermission("essentials.worlds.<worldname>", "Allows players access to a specific world.", Collections.singletonList("home")),
                new ExternalPluginPermission("essentials.worlds.<worldname>", "Allows players access to a specific world.", Collections.singletonList("tp")),
                new ExternalPluginPermission("essentials.worlds.<worldname>", "Allows players access to a specific world.", Collections.singletonList("tpa")),
                new ExternalPluginPermission("essentials.worlds.<worldname>", "Allows players access to a specific world.", Collections.singletonList("tpaall")),
                new ExternalPluginPermission("essentials.worlds.<worldname>", "Allows players access to a specific world.", Collections.singletonList("tpahere")),
                new ExternalPluginPermission("essentials.worlds.<worldname>", "Allows players access to a specific world.", Collections.singletonList("tpall")),
                new ExternalPluginPermission("essentials.worlds.<worldname>", "Allows players access to a specific world.", Collections.singletonList("tphere")),
                new ExternalPluginPermission("essentials.worlds.<worldname>", "Allows players access to a specific world.", Collections.singletonList("tpo")),
                new ExternalPluginPermission("essentials.worlds.<worldname>", "Allows players access to a specific world.", Collections.singletonList("tpohere")),
                new ExternalPluginPermission("essentials.worlds.<worldname>", "Allows players access to a specific world.", Collections.singletonList("world")),
                new ExternalPluginPermission("essentials.itemspawn.meta-chapter-[chapter]", "Allow access to the Allows spawning of specific books only, from book.txt./give command.", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.ban.notify", "Players with this permission will receive a notification when a ban is set.", Collections.singletonList("ban")),
                new ExternalPluginPermission("essentials.banip.notify", "Players with this permission will receive a notification when an IP ban is set.", Collections.singletonList("banip")),
                new ExternalPluginPermission("essentials.ban.notify", "Players with this permission will receive a notification when a ban is set.", Collections.singletonList("tempban")),
                new ExternalPluginPermission("essentials.ban.notify", "Players with this permission will receive a notification when a ban is removed.", Collections.singletonList("unban")),
                new ExternalPluginPermission("essentials.banip.notify", "Players with this permission will receive a notification when an IP ban is removed.", Collections.singletonList("unbanip")),
                new ExternalPluginPermission("essentials.enchantments.[enchantmentname]", "Allows access to each enchantment type.", Collections.singletonList("enchant")),
                new ExternalPluginPermission("essentials.enchantments.[enchantmentname]", "Allows access to each enchantment type.", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.enchantments.[enchantmentname]", "Allows access to each enchantment type.", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.enchantments.allowunsafe", "If enabled in the config, this permission allows unsafe enchantments.", Collections.singletonList("enchant")),
                new ExternalPluginPermission("essentials.enchantments.allowunsafe", "If enabled in the config, this permission allows unsafe enchantments.", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.enchantments.allowunsafe", "If enabled in the config, this permission allows unsafe enchantments.", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.itemspawn.item-<itemname>", "If permission-based-item-spawn: Spawn <itemname>", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.itemspawn.item-[itemid]", "If permission-based-item-spawn: Spawn [itemid]", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.itemspawn.item-[itemid]", "If permission-based-item-spawn: Spawn [itemid]", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.itemspawn.item-[itemname]", "If permission-based-item-spawn: Spawn [itemname]", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.itemspawn.item-all", "If permission-based-item-spawn: Spawn all items", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.itemspawn.item-all", "If permission-based-item-spawn: Spawn all items.", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.itemspawn.meta-author", "Allow 'author' meta to be used in item spawning.", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.itemspawn.meta-author", "Allow 'author' meta to be used in item spawning.", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.itemspawn.meta-book", "Allows spawning of books with pre-filled content from books.txt", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.itemspawn.meta-book", "Allows spawning of books with pre-filled content from books.txt", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.itemspawn.meta-firework", "Allow specific meta for fireworks.", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.itemspawn.meta-firework", "Allow specific meta for fireworks.", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.itemspawn.meta-head", "Allows spawning of mob heads.", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.itemspawn.meta-head", "Allows spawning of mob heads.", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.itemspawn.meta-lore", "Allow 'lore' meta to be used in item spawning.", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.itemspawn.meta-lore", "Allow 'lore' meta to be used in item spawning.", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.itemspawn.meta-title", "Allow 'title' meta to be used in item spawning.", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.itemspawn.meta-title", "Allow 'title' meta to be used in item spawning.", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.oversizedstacks", "Allows spawning of stacks above normal max stack size", Collections.singletonList("give")),
                new ExternalPluginPermission("essentials.oversizedstacks", "Allows spawning of stacks above normal max stack size", Collections.singletonList("item")),
                new ExternalPluginPermission("essentials.oversizedstacks", "Allows spawning of oversized stacks.", Collections.singletonList("more")),
                new ExternalPluginPermission("essentials.vanish.effect", "Allow adding potion effects when someone goes into vanish", Collections.singletonList("vanish")),
                new ExternalPluginPermission("essentials.vanish.interact", "Allow interacting with vanished players", Collections.singletonList("vanish")),
                new ExternalPluginPermission("essentials.back.into.<worldname>", "Allows access to /back when the destination location is within the specified world", Collections.singletonList("back")),
                new ExternalPluginPermission("essentials.whois.ip", "Allow seeing someones ip address in the /whois command.", Collections.singletonList("whois")),
                new ExternalPluginPermission("essentials.gamemode.creative", "Allow access to the /gamemode creative command. Also requires essentials.gamemode", Collections.singletonList("gamemode")),
                new ExternalPluginPermission("essentials.gamemode.survival", "Allow access to the /gamemode survival command. Also requires essentials.gamemode", Collections.singletonList("gamemode")),
                new ExternalPluginPermission("essentials.gamemode.adventure", "Allow access to the /gamemode adventure command. Also requires essentials.gamemode", Collections.singletonList("gamemode")),
                new ExternalPluginPermission("essentials.gamemode.spectator", "Allow access to the /gamemode spectator command. Also requires essentials.gamemode", Collections.singletonList("gamemode")),
                new ExternalPluginPermission("essentials.nick.allowunsafe", "If a player has this, they can set their username to any value. Use with caution, as this has the potential to break userdata files.", Collections.singletonList("nick")),
                new ExternalPluginPermission("essentials.msgtoggle.bypass", "This permission allows you to send private messages to users that have disabled them with /msgtoggle.", Collections.singletonList("msg")),
                new ExternalPluginPermission("essentials.tpauto.others", "Allow using /tpauto for other players", Collections.singletonList("tpauto")),
                new ExternalPluginPermission("essentials.nick.color", "Allows to use colors in the /nick command", Collections.singletonList("nick")),
                new ExternalPluginPermission("essentials.nick.magic", "Allows to use magic effect in the /nick command", Collections.singletonList("nick")),
                new ExternalPluginPermission("essentials.nick.format", "Allows to use formatting in the /nick command", Collections.singletonList("nick")),
                new ExternalPluginPermission("essentials.keepinv", "Allows the user to keep their inventory on death, instead of dropping it.", Collections.singletonList("back")),
                new ExternalPluginPermission("essentials.back.others", "Allows the user to execute the /back command for other players", Collections.singletonList("back")),
                new ExternalPluginPermission("essentials.mute.notify", "Get notified when an muted player tries to talk", Collections.singletonList("mute")),
                new ExternalPluginPermission("essentials.balancetop.exclude", "Players with this permission are excluded from the balancetop", Collections.singletonList("balancetop")),
                new ExternalPluginPermission("essentials.hat.prevent-type.<item-name>", "Give this permission to users to prevent them using this type of item in /hat", Collections.singletonList("hat")),
                new ExternalPluginPermission("essentials.hat.ignore-binding", "Disable blocking the removing of hats with curse of binding", Collections.singletonList("hat")),
                new ExternalPluginPermission("essentials.playtime", "Shows a player's time played in game", Collections.singletonList("playtime")),
                new ExternalPluginPermission("essentials.playtime.others", "Shows a player's time played in game", Collections.singletonList("playtime")
                )), ver));
    }

    public void injectVaultPermissions(String ver) {
        addHookup(new ExternalPlugin("Vault", "&aVault", "Vault is a Permissions, Chat, & Economy API to give plugins easy hooks into these systems without needing to hook or depend on each individual plugin themselves.", Material.CHEST, Arrays.asList(
                new ExternalPluginPermission("vault.admin", "Allows access to vault info and conversion commands", Arrays.asList("vault-info", "vault-conversion")),
                new ExternalPluginPermission("vault.update", "Anyone with this permission will be notified when Vault is out-dated")
        ), ver));
    }

    public void injectEssentialsSpawnPermissions(String ver) {
        addHookup(new ExternalPlugin("EssentialsX Spawn", "&fEssentialsX &bSpawn", "Spawnpoint control, per-player spawns from EssentialsX.", Material.RED_BED, Arrays.asList(
                new ExternalPluginPermission("essentials.setspawn", "Allow access to the /setspawn command.", Collections.singletonList("setspawn")),
                new ExternalPluginPermission("essentials.spawn", "Allow access to the /spawn command.", Collections.singletonList("spawn")),
                new ExternalPluginPermission("essentials.spawn-on-join.exempt", "Allow to be exempt from forced teleporting to spawn on join"),
                new ExternalPluginPermission("essentials.spawn.others", "Allows you to teleport other people to spawn", Collections.singletonList("spawn"))
        ), ver));
    }

    private void injectEssentialsChatPermissions(String ver) {
        addHookup(new ExternalPlugin("EssentialsX Chat", "&fEssentialsX &eChat", "Chat formatting, local chat from EssentialsX.", Material.PAPER, Arrays.asList(
                new ExternalPluginPermission("essentials.chat.color", "This allows you to color your chat messages in any color using color codes, NOT including hex colors (&#RRGGBB)."),
                new ExternalPluginPermission("essentials.chat.<color>", "This allows you to color your chat messages in <color> using color codes."),
                new ExternalPluginPermission("essentials.chat.format", "This allows you to format your chat messages using format codes."),
                new ExternalPluginPermission("essentials.chat.magic", "This allows you to use the matrix/magic color in your chat messages."),
                new ExternalPluginPermission("essentials.chat.rgb", "This allows you to use hex color formatting in your chat messages. Format is &#RRGGBB."),
                new ExternalPluginPermission("essentials.chat.question", "This allows you to send global questions, used if a chat-radius is configured."),
                new ExternalPluginPermission("essentials.chat.shout", "This allows you to send global messages, used if a chat-raidus is configured."),
                new ExternalPluginPermission("essentials.toggleshout", "Toggles whether you are talking in shout mode."),
                new ExternalPluginPermission("essentials.toggleshout.others", "Toggles shout mode for other players."),
                new ExternalPluginPermission("essentials.chat.spy", "A permission designed for admins, to intercept all local messages (ignoring the chat-radius)."),
                new ExternalPluginPermission("essentials.chat.url", "This allows you to use urls in your chat messages."),
                new ExternalPluginPermission("essentials.chat.local", "Allow to send messages to local chat. Given to all players by default."),
                new ExternalPluginPermission("essentials.chat.receive.local", "Permission allowing to recieve local chat. Given to all players by default."),
                new ExternalPluginPermission("essentials.chat.receive.shout", "Permission allowing to recieve shouts. Given to all players by default."),
                new ExternalPluginPermission("essentials.chat.receive.question", "Permission allowing to recieve questions. Given to all players by default.")), ver));
    }

    public void loadPermissionsFromKnownPlugins() {
        Plugin pl = rpa.getPlugin().getServer().getPluginManager().getPlugin("Essentials"); if (pl != null) { injectEssentialsXPermissions(pl.getDescription().getVersion()); }

        pl = rpa.getPlugin().getServer().getPluginManager().getPlugin("EssentialsSpawn"); if (pl != null) { injectEssentialsSpawnPermissions(pl.getDescription().getVersion()); }

        pl = rpa.getPlugin().getServer().getPluginManager().getPlugin("EssentialsChat"); if (pl != null) { injectEssentialsChatPermissions(pl.getDescription().getVersion()); }
    }
}
